# Server
server:
  port: 8888

# Spring Cloud Config Server
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@github.com/MMarzouk2025/tabaa-configuration
          search-paths: /{application}/{profile}


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, refresh

