# server
server:
  port: 8888

# spring cloud config server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MMarzouk2025/tabaa-central-config-server
#          search-paths: config
          username: MMarzouk2025
          password: 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
